#!/bin/bash

ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:7e:a3:3f brd ff:ff:ff:ff:ff:ff
    inet 192.168.159.132/24 brd 192.168.159.255 scope global dynamic noprefixroute ens33
       valid_lft 1722sec preferred_lft 1722sec
    inet6 fe80::20c:29ff:fe7e:a33f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever


dig debian.org
; <<>> DiG 9.11.5-P4-5.1+deb10u6-Debian <<>> debian.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12369
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0005, udp: 512
;; QUESTION SECTION:
;debian.org.			IN	A

;; ANSWER SECTION:
debian.org.		5	IN	A	128.31.0.62
debian.org.		5	IN	A	130.89.148.77
debian.org.		5	IN	A	149.20.4.15

;; Query time: 23 msec
;; SERVER: 192.168.159.2#53(192.168.159.2)
;; WHEN: Thu Mar 03 15:14:46 EST 2022
;; MSG SIZE  rcvd: 87


netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      482/cupsd           
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      863/exim4           
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      880/smbd            
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      880/smbd            
tcp6       0      0 ::1:631                 :::*                    LISTEN      482/cupsd           
tcp6       0      0 ::1:25                  :::*                    LISTEN      863/exim4           
tcp6       0      0 :::445                  :::*                    LISTEN      880/smbd            
tcp6       0      0 :::139                  :::*                    LISTEN      880/smbd            
udp        0      0 0.0.0.0:68              0.0.0.0:*                           576/dhclient        
udp        0      0 192.168.159.255:137     0.0.0.0:*                           608/nmbd            
udp        0      0 192.168.159.132:137     0.0.0.0:*                           608/nmbd            
udp        0      0 0.0.0.0:137             0.0.0.0:*                           608/nmbd            
udp        0      0 192.168.159.255:138     0.0.0.0:*                           608/nmbd            
udp        0      0 192.168.159.132:138     0.0.0.0:*                           608/nmbd            
udp        0      0 0.0.0.0:138             0.0.0.0:*                           608/nmbd            
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           477/avahi-daemon: r 
udp        0      0 0.0.0.0:41380           0.0.0.0:*                           477/avahi-daemon: r 
udp        0      0 0.0.0.0:631             0.0.0.0:*                           532/cups-browsed    
udp6       0      0 :::5353                 :::*                                477/avahi-daemon: r 
udp6       0      0 :::43468                :::*                                477/avahi-daemon: r 
